### ISSUE TITLE
安装完后 var WechatAPI = require('co-wechat-api') 这步直接报错。提示util.promisify没有

### ISSUE THREAD

**Issue by duohudie** [node-webot/co-wechat-api#101]
![image](https://user-images.githubusercontent.com/34697934/42484695-d14bfa76-8426-11e8-9c6c-11c7a4f63c8a.png)，
大佬，是我使用方法错了，还是这个co-wechat-api出问题了，好像错误发生在这个文件api_media.js

**Comment by JacksonTian** [comment]
你的版本不对。
