### ISSUE TITLE
token全局变量的存储，在存储的时候是否还需要判断过期呢

### ISSUE THREAD

**Issue by liuyiji** [node-webot/co-wechat-api#107]
* 当多进程时，token 需要全局维护，以下为保存 token 的接口。
   * ```
   * var api = new API('appid', 'secret', async function () {
   *   // 传入一个获取全局 token 的方法
   *   var txt = await fs.readFile('access_token.txt', 'utf8');
========= 在这里是否还需要做token 7200毫秒的过期判断呢？
   *   return JSON.parse(txt);
   * }, async function (token) {
   *   // 请将 token 存储到全局，跨进程、跨机器级别的全局，比如写到数据库、redis等
   *   // 这样才能在cluster模式及多机情况下使用，以下为写入到文件的示例
   *   await fs.writeFile('access_token.txt', JSON.stringify(token));
   * });

**Comment by JacksonTian** [comment]
框架会判断。
