### ISSUE TITLE
更新永久图文素材 updateNewsMaterial 的 url 错了

### ISSUE THREAD

**Issue by kushao** [node-webot/co-wechat-api#117]
exports.updateNewsMaterial = async function (news) {
  const { accessToken } = await this.ensureAccessToken();
  var url = this.prefix + 'material/add_news?access_token=' + accessToken;
  return this.request(url, postJSON(news));
};

应该是

exports.updateNewsMaterial = async function (news) {
  const { accessToken } = await this.ensureAccessToken();
  var url = this.prefix + 'material/update_news?access_token=' + accessToken;
  return this.request(url, postJSON(news));
};

**Comment by Suley** [comment]
确实错了，没人更新吗？

**Comment by brightonzhang** [comment]
已提交PR

**Comment by JacksonTian** [comment]
已合并，待发布
