### ISSUE TITLE
getJsConfig 不支持最新的 "openTagList"（开放标签）参数

### ISSUE THREAD

**Issue by GeorgeChan** [node-webot/co-wechat-api#126]
getJsConfig 配置功能，不支持最新的 "openTagList"（开放标签）参数，https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/Wechat_Open_Tag.html

**Comment by welchwsy** [comment]
getJsConfig 方法改一下，具体见 https://github.com/node-webot/co-wechat-api/pull/128

**Comment by JacksonTian** [comment]
已合并，等发布
