### ISSUE TITLE
应该想办法用 bluebird 之类的把 api 包装成 Promise

### ISSUE THREAD

**Issue by cncolder** [node-webot/co-wechat-api#17]
koa@1 实在是一种误导, 许多项目跟风基于 co 构建.
现在 koa@2 全面切换到 Promise 和 async function 了.

与其把所有方法都写成 generator, 不如全部返回 Promise 适用性更广.
比如用 bluebird 把 wechat-api 包装一下.

**Comment by magicxie** [comment]
貌似有nowrap分支就是干这个事情的？

**Comment by nick-ma** [comment]
这个无所谓吧。
自己想用Promise的话，可以包一下。
co虽然是过度阶段的产物，但是随着广泛的应用，也会反向的影响到标准的制定。
反正，总归能用就行。
当原生的Promise足够稳定，强大的时候，会考虑升级为全Promise模式的。

**Comment by JacksonTian** [comment]
等ES7吧。
