### ISSUE TITLE
异常抛出没有捕获

### ISSUE THREAD

**Issue by wfsovereign** [node-webot/co-wechat-api#20]
sendTemplate 接口调用的 request方法里面抛出了异常，但是在sendTemplate接口中并没有捕获异常，导致外部调用时不能捕获该异常。
请问，您的设计就是不让外部捕获这个异常吗？或者关于捕获这个异常您有什么好办法呢

**Comment by wfsovereign** [comment]
犯傻了我- -

**Comment by JacksonTian** [comment]
么么。
