### ISSUE TITLE
似乎所有 POST 请求都有 Bug?

### ISSUE THREAD

**Issue by mouhong** [node-webot/co-wechat-api#32]
co-wechat-api 版本: 2.4.2
httpx 版本: 2.0.0

我使用`uploadMedia`时一直都是提示"missing media data hint"，看了下 co-wechat-api 的代码，似乎所有的 POST API 都可能有问题？

先看 lib/api_media.js
https://github.com/node-webot/co-wechat-api/blob/master/lib/api_media.js#L32

它给 this.request 传的 opts 中 http method 是用 `type` 来指定的。
在 api_common.js 中，它原样传给 httpx。

再看 httpx 的 index.js:
https://github.com/JacksonTian/httpx/blob/master/index.js#L29

它接受的是`method`属性名，而不是`type`。

这个是 bug ?

Thanks

**Comment by JacksonTian** [comment]
代码迁移的问题。type是urllib用的。欢迎PR。

**Comment by JacksonTian** [comment]
已经修复了
