### ISSUE TITLE
async 返回错误

### ISSUE THREAD

**Issue by lk125454242** [node-webot/co-wechat-api#49]
API： batchGetUsers 
环境： node v8.1.3
问题描述： 
同样的openid 在使 co + generator 的时候 返回结果正常
修改为 anync + await 之后 返回结果始终为一个 空对象 
表示重构失败，完全不知所以然，忘解答

**Comment by JacksonTian** [comment]
不是空对象，是 Promise 对象。放段代码看看 怎么写的

**Comment by lk125454242** [comment]
好的，谢谢~
` 
                console.log(
                    '111111111111'
                );
                let wx_info = await wx.api.batchGetUsers([openid]);
                _.assign(info, wx_info[0]);
                console.log(
                    '3333333333333'
                );
                if(_student){
                    await models.WX.findOrCreate({
`

**Comment by lk125454242** [comment]
`let wx_info = await wx.api.batchGetUsers([openid]);`

**Comment by JacksonTian** [comment]
其他 API 呢 正常的吧。

**Comment by lk125454242** [comment]
sendText 也是,其他的还没开始重构代码,还不知道。

**Comment by JacksonTian** [comment]
先关闭，如有问题请 re-open
