### ISSUE TITLE
模板消息sendTemplate官方增加了小程序配置

### ISSUE THREAD

**Issue by xiaodonghui** [node-webot/co-wechat-api#51]
参数 | 是否必填 | 说明
-- | -- | --
touser | 是 | 接收者openid
template_id | 是 | 模板ID
url | 否 | 模板跳转链接
miniprogram | 否 | 跳小程序所需数据，不需跳小程序可不用传该数据
appid | 是 | 所需跳转到的小程序appid（该小程序appid必须与发模板消息的公众号是绑定关联关系）
pagepath | 是 | 所需跳转到小程序的具体页面路径，支持带参数,（示例index?foo=bar）
data | 是 | 模板数据

   注：url和miniprogram都是非必填字段，若都不传则模板无跳转；若都传，会优先跳转至小程序。开发者可根据实际需要选择其中一种跳转方式即可。当用户的微信客户端版本不支持跳小程序时，将会跳转至url。

现在的接口不能实现小程序的配置，并且topColor这个参数也去掉了。

**Comment by JacksonTian** [comment]
发 pull request 吧。
