### ISSUE TITLE
增加接口推送订阅模板消息给到授权微信用户

### ISSUE THREAD

**Issue by dcboy** [node-webot/co-wechat-api#60]
接口:
https://api.weixin.qq.com/cgi-bin/message/template/subscribe?access_token=ACCESS_TOKEN

文档:
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1500374289_66bvB

**Comment by JacksonTian** [comment]
Would like to see Pull Request? It is very easy to add new API like this https://github.com/node-webot/co-wechat-api/blob/master/lib/api_ip.js .
