### ISSUE TITLE
获取微信用户信息json parse error问题

### ISSUE THREAD

**Issue by xiaodonghui** [node-webot/co-wechat-api#63]
{ WeChatAPIError: JSON.parse error. buffer is {"subscribe":1,"openid":"ogW8rt6i8BmyHaXvleP5SBULysSk","nickname":"Íõ¾ü","sex":1,"language":"zh_CN","city":"y?v\\","province":"l?S","country":"","headimgurl":"http:\/\/wx.qlogo.cn\/mmopen\/Q3auHgzwzM4nXzLJEGv1SUt5ibMeibUjmaK45y06UOtaKDc2NgjvjjnsiccgwMPyKOwvstIKA85bM7zziac5m9zmfw\/0","subscribe_time":1504246660,"unionid":"oKfK5s5qiqgWMHaeJ6f3sy5TYvx8","remark":"","groupid":0,"tagid_list":[]}

现在很多这种错误，我看了下wechat-api的issues说是解决了，co的这个能解决一下吗？

**Comment by JacksonTian** [comment]
是因为这个用户的信息里包含了一些非法字符吧。。。

**Comment by xiaodonghui** [comment]
https://github.com/node-modules/urllib/pull/77
这个里面有说到做了处理，我看co-wechat-api的api_common.js和wechat-api的不一样，是不是wechat-api的解决了这个问题？

**Comment by xream** [comment]
我也遇到了这个问题

```
{"subscribe":1,"openid":"ocXSCwBTVyFYe5JUrY37iguzP6GI","nickname":"都都宝","sex":1,"language":"zh_CN","city":"\b","province":"\n61.151.217.158","country":"","headimgurl":"http:\/\/wx.qlogo.cn\/mmopen\/9Wjh4pAQBFpibic2riaHibnuE39fZwrZibtolbej8J9cVwzTnFicibNr6A1K4DYxtq0ucmrTEqlb5jrXy5gIPmL1o4RId9LK9B9hc7X\/0","subscribe_time":1509460366,"unionid":"o0pOfw-nH_4WBGiwMBrZWUgwJ8Do","remark":"","groupid":0,"tagid_list":[]}
```

**Comment by xiaodonghui** [comment]
问题已经解决，感谢。

**Comment by xiaodonghui** [comment]
发现新的问题了，所有/这个都被替换成\/这个了
http:\/\/weixin.qq.com\/q\/02T3ooYRGnf4318qfD1q17
这个问题造成所有头像，二维码等都无法使用了。。。。

**Comment by xream** [comment]
@xiaodonghui 嗯 我手动替换了...

**Comment by xiaodonghui** [comment]
@xream 没有完美一点的解决办法吗。。

**Comment by xiaodonghui** [comment]
@JacksonTian 发现emoji都被替换成无法识别的了。。

**Comment by xream** [comment]
@xiaodonghui 我试了下没有发现问题...来个例子?

**Comment by xiaodonghui** [comment]
我的错，看错了

**Comment by JacksonTian** [comment]
? 问题解决了吗？

**Comment by xiaodonghui** [comment]
@JacksonTian 又有新的了，如下
{ WeChatAPIError: JSON.parse error. buffer is {"subscribe":1,"openid":"ogW8rt_CsZElHizhxelZBurdDZ3M","nickname":"\"安若空   平及淡\"","sex":2,"language":"zh_CN","city":"马鞍山","province":"安徽","country":"中国","headimgurl":"http:\/\/wx.qlogo.cn\/mmopen\/ajNVdqHZLLCMCxzIs8W63LYDfBicUpcenh6hfGLX6yg5nwU4GEzIuuDFuicsk1OFKXhzEnRXl8DxibtGHa90PcD10HLV78CapDBgd3WGG9080w\/0","subscribe_time":1510130851,"unionid":"oKfK5s0fbwX_aCkRwcUZcWl-C9ME","remark":"","groupid":0,"tagid_list":[]}

**Comment by JacksonTian** [comment]
我只能说腾讯太他妈的傻逼了。连个 JSON 格式都搞不定。

**Comment by xiaodonghui** [comment]
问题是这种的还挺多，不是少数。。。

**Comment by JacksonTian** [comment]
{"subscribe":1,"openid":"ogW8rt_CsZElHizhxelZBurdDZ3M","nickname":"\"安若空 平及淡\"","sex":2,"language":"zh_CN","city":"马鞍山","province":"安徽","country":"中国","headimgurl":"http:\/\/wx.qlogo.cn\/mmopen\/ajNVdqHZLLCMCxzIs8W63LYDfBicUpcenh6hfGLX6yg5nwU4GEzIuuDFuicsk1OFKXhzEnRXl8DxibtGHa90PcD10HLV78CapDBgd3WGG9080w\/0","subscribe_time":1510130851,"unionid":"oKfK5s0fbwX_aCkRwcUZcWl-C9ME","remark":"","groupid":0,"tagid_list":[]} 这个格式 JSON 能解析的啊，怎么会报错？

**Comment by xiaodonghui** [comment]
我也试了，能解析，但是wechat-api报的错，不知道是不是转义弄的？
···
{ WeChatAPIError: JSON.parse error. buffer is {"subscribe":1,"openid":"o6tfEw_IGYnrJMotu6eHI1Q9LneE","nickname":"\"愤怒💢的小鸟🐤","sex":1,"language":"zh_CN","city":"锡达拉皮兹","province":"爱荷华","country":"美国","headimgurl":"http:\/\/wx.qlogo.cn\/mmopen\/9UjCmequjU8o6Ulj5mJdkouP9xH1AicDiaJIpjWkMxiaYMCGTt7DUhEtCSJyqvbnLbNPEIBICoaLlLicjMrwhyAqbA\/0","subscribe_time":1474591542,"remark":"","groupid":0,"tagid_list":[]}
···

**Comment by xiaodonghui** [comment]
我发现是替换后不能json.parse了

**Comment by xiaodonghui** [comment]
@JacksonTian 我发现是替换后造成的不能parse
替换前
```
{"subscribe":1,"openid":"ogW8rtwp4dpOCU1xVJ6x_UMkBDHg","nickname":"💕\"匆匆岁月\"🐒","sex":2,"language":"zh_CN","city":"马鞍山","province":"安徽","country":"中国","headimgurl":"http:\/\/wx.qlogo.cn\/mmopen\/PiajxSqBRaEL94jeQzUfZcYTvicA0uHBq5Oaib0OfP1S3LvDd8yBiagTx0InmwoF8MOticgibyuVwhOBekP18r79KibZg\/0","subscribe_time":1511323966,"unionid":"oKfK5s09PkKrZPG89TzWP0ag-G0E","remark":"","groupid":0,"tagid_list":[]}
```
替换后
```
{"subscribe":1,"openid":"ogW8rtwp4dpOCU1xVJ6x_UMkBDHg","nickname":"💕\\"匆匆岁月\\"🐒","sex":2,"language":"zh_CN","city":"马鞍山","province":"安徽","country":"中国","headimgurl":"http:\\/\\/wx.qlogo.cn\\/mmopen\\/PiajxSqBRaEL94jeQzUfZcYTvicA0uHBq5Oaib0OfP1S3LvDd8yBiagTx0InmwoF8MOticgibyuVwhOBekP18r79KibZg\\/0","subscribe_time":1511323966,"unionid":"oKfK5s09PkKrZPG89TzWP0ag-G0E","remark":"","groupid":0,"tagid_list":[]}
```

**Comment by JacksonTian** [comment]
发布了一个新的版本，看看是否ok

**Comment by xiaodonghui** [comment]
@JacksonTian
