### ISSUE TITLE
node 8以上版本不支持？

### ISSUE THREAD

**Issue by FujiBilly** [node-webot/co-wechat-api#65]
nodejs 8.0.0环境下调用getTicket接口回调返回的是空，拿不到从微信获取的数据

**Comment by JacksonTian** [comment]
用的什么版本？

**Comment by wangbinxiang** [comment]
包一层co就解决了
**
const _getJsConfig = wechatApi.getJsConfig

wechatApi.getJsConfig = function (param) {
  return co(_getJsConfig.call(wechatApi, param))
}
**

**Comment by JacksonTian** [comment]
支持了吧
