### ISSUE TITLE
发送模板消息时 发送没有内容

### ISSUE THREAD

**Issue by Messilimeng** [node-webot/co-wechat-api#70]
![image](https://user-images.githubusercontent.com/12272166/34192914-cf63a586-e58b-11e7-867a-25222d42b166.png)
这样不兼容以前没有小程序的跳转

**Comment by JacksonTian** [comment]
有一个新的 API。

**Comment by Messilimeng** [comment]
@JacksonTian 哪一个啊请问

**Comment by JacksonTian** [comment]
sendMini*

**Comment by Messilimeng** [comment]
@JacksonTian 
![image](https://user-images.githubusercontent.com/12272166/34244109-dd4b3de8-e65e-11e7-9cee-e69e3b87252f.png)
我是没有小程序的 
 就是小程序 appid 和path 两个参数是不用传的吗

**Comment by Cweili** [comment]
@JacksonTian 这样的不能向下兼容的 api 变更根据 semver 还请变更大版本号，项目添加依赖时候使用了允许小版本号更新的规则导致模板消息没内容了……

**Comment by befinal** [comment]
@Messilimeng @Cweili 
#74 已修复，兼容老版本，同时支持小程序跳转
