### ISSUE TITLE
npm 默认版本问题

### ISSUE THREAD

**Issue by se7enups** [node-webot/co-wechat-api#78]
使用npm i co-wechat-api时，**默认导入的是2.7.2版本**
现在**最新的版本已经是^3了**
最大的差异就在于2版本的是使用的generator，3版本的使用的是async await。
导致在koa中引用的时候一直返回空值。查看源码才发现问题

就算npm默认使用2版本号，**希望能至少在文档里提一下注意事项**。

另外，谢谢，封装的代码很好用

**Comment by JacksonTian** [comment]
我修正了 latest 的指向。这个是 npm 的默认行为，latest 指向最后发布的版本。

不过我还是建议你指定为 ^3 就好。
