### ISSUE TITLE
sendTemplate 接口返回 msgid 精度丢失

### ISSUE THREAD

**Issue by zzdhidden** [node-webot/co-wechat-api#89]
返回结果：

     {"errcode":0,"errmsg":"ok","msgid":271781022721654784}

由于数字太大了，JSON.parse 之后精度就丢失了，变成了 271781022721654800，目前request接口没提供预处理结果的方法，不好自己修正。

**Comment by JacksonTian** [comment]
> 271781022721654784 > Number.MAX_SAFE_INTEGER 是这样的。

我想想怎么处理比较好。

**Comment by imerovingian** [comment]
```
edit ->api_common.js
add ->const JSONbig = require('json-bigint');
modify ->
try {
                data = JSONbig.parse(replaceJSONCtlChars(origin));
            } 
```

**Comment by JacksonTian** [comment]
@imerovingian 来个 PR 吧
